/**
 * deposit-sepolia.ts — Deposits real USDC into PrivateBalance contract on Base Sepolia.
 *
 * Flow:
 *   1. Agent approves PrivateBalance to spend USDC
 *   2. Agent calls deposit(amount) on PrivateBalance
 *   3. Contract pulls USDC via transferFrom and queues a Deposit action
 *   4. Mock MPC service picks up the Deposit action and creates the balance commitment
 *
 * Usage: pnpm run deposit:sepolia
 * Requires: .env.sepolia (generated by deploy-sepolia.ts)
 */

import { config } from "dotenv";
config();

import {
  createPublicClient,
  createWalletClient,
  http,
  parseAbi,
  defineChain,
} from "viem";
import { baseSepolia } from "viem/chains";
import { privateKeyToAccount } from "viem/accounts";

// ── Configuration ──────────────────────────────────────────────────────────────

const RPC_URL = process.env.RPC_URL || "https://sepolia.base.org";
const CHAIN_ID = parseInt(process.env.CHAIN_ID || "84532");
const AGENT_KEY = process.env.AGENT_PRIVATE_KEY as `0x${string}`;
const USDC_ADDRESS = process.env.USDC_ADDRESS as `0x${string}`;
const PRIVATE_BALANCE_ADDRESS = process.env.PRIVATE_BALANCE_ADDRESS as `0x${string}`;

if (!AGENT_KEY || !USDC_ADDRESS || !PRIVATE_BALANCE_ADDRESS) {
  console.error("Missing required env vars. Run 'pnpm run deploy:sepolia' first.");
  process.exit(1);
}

// Amount to deposit (default: 20 USDC = 20_000_000 in 6-decimal units)
const DEPOSIT_AMOUNT = BigInt(process.env.DEPOSIT_AMOUNT || "20000000");

// ── Chain & Clients ────────────────────────────────────────────────────────────

const chain = CHAIN_ID === 84532
  ? defineChain({ ...baseSepolia, rpcUrls: { default: { http: [RPC_URL] } } })
  : defineChain({
      id: CHAIN_ID,
      name: "Anvil",
      nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
      rpcUrls: { default: { http: [RPC_URL] } },
    });

const agentAccount = privateKeyToAccount(AGENT_KEY);
const publicClient = createPublicClient({ chain, transport: http(RPC_URL) });
const walletClient = createWalletClient({
  account: agentAccount,
  chain,
  transport: http(RPC_URL),
});

const erc20Abi = parseAbi([
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
]);

const depositAbi = parseAbi([
  "function deposit(uint256 amount) returns (uint256)",
  "function getBalanceCommitment(address user) view returns (uint256)",
  "function getActionQueueSize() view returns (uint256)",
]);

// ── Main ───────────────────────────────────────────────────────────────────────

async function main() {
  console.log(`[Deposit] Agent: ${agentAccount.address}`);
  console.log(`[Deposit] USDC: ${USDC_ADDRESS}`);
  console.log(`[Deposit] PrivateBalance: ${PRIVATE_BALANCE_ADDRESS}`);
  console.log(`[Deposit] Amount: ${Number(DEPOSIT_AMOUNT) / 1e6} USDC\n`);

  // 1. Check USDC balance
  const usdcBalance = await publicClient.readContract({
    address: USDC_ADDRESS,
    abi: erc20Abi,
    functionName: "balanceOf",
    args: [agentAccount.address],
  });
  console.log(`[Deposit] Agent USDC balance: ${Number(usdcBalance) / 1e6} USDC`);

  if (usdcBalance < DEPOSIT_AMOUNT) {
    console.error(`[Deposit] Insufficient USDC. Need ${Number(DEPOSIT_AMOUNT) / 1e6}, have ${Number(usdcBalance) / 1e6}`);
    process.exit(1);
  }

  // 2. Check current allowance
  const currentAllowance = await publicClient.readContract({
    address: USDC_ADDRESS,
    abi: erc20Abi,
    functionName: "allowance",
    args: [agentAccount.address, PRIVATE_BALANCE_ADDRESS],
  });
  console.log(`[Deposit] Current allowance: ${Number(currentAllowance) / 1e6} USDC`);

  // 3. Approve if needed
  if (currentAllowance < DEPOSIT_AMOUNT) {
    console.log(`[Deposit] Approving ${Number(DEPOSIT_AMOUNT) / 1e6} USDC...`);
    const approveTx = await walletClient.writeContract({
      address: USDC_ADDRESS,
      abi: erc20Abi,
      functionName: "approve",
      args: [PRIVATE_BALANCE_ADDRESS, DEPOSIT_AMOUNT],
    });
    const approveReceipt = await publicClient.waitForTransactionReceipt({ hash: approveTx });
    console.log(`[Deposit] Approve confirmed: ${approveTx} (block ${approveReceipt.blockNumber})`);
  } else {
    console.log("[Deposit] Allowance sufficient, skipping approve");
  }

  // 4. Check queue size before deposit
  const queueBefore = await publicClient.readContract({
    address: PRIVATE_BALANCE_ADDRESS,
    abi: depositAbi,
    functionName: "getActionQueueSize",
  });
  console.log(`[Deposit] Queue size before: ${queueBefore}`);

  // 5. Call deposit
  console.log(`[Deposit] Depositing ${Number(DEPOSIT_AMOUNT) / 1e6} USDC...`);
  const depositTx = await walletClient.writeContract({
    address: PRIVATE_BALANCE_ADDRESS,
    abi: depositAbi,
    functionName: "deposit",
    args: [DEPOSIT_AMOUNT],
  });
  const depositReceipt = await publicClient.waitForTransactionReceipt({ hash: depositTx });
  console.log(`[Deposit] Deposit confirmed: ${depositTx} (block ${depositReceipt.blockNumber})`);

  // 6. Verify
  const queueAfter = await publicClient.readContract({
    address: PRIVATE_BALANCE_ADDRESS,
    abi: depositAbi,
    functionName: "getActionQueueSize",
  });
  console.log(`[Deposit] Queue size after: ${queueAfter}`);

  const usdcAfter = await publicClient.readContract({
    address: USDC_ADDRESS,
    abi: erc20Abi,
    functionName: "balanceOf",
    args: [agentAccount.address],
  });
  console.log(`[Deposit] Agent USDC balance after: ${Number(usdcAfter) / 1e6} USDC`);

  const contractUsdc = await publicClient.readContract({
    address: USDC_ADDRESS,
    abi: erc20Abi,
    functionName: "balanceOf",
    args: [PRIVATE_BALANCE_ADDRESS],
  });
  console.log(`[Deposit] PrivateBalance contract USDC: ${Number(contractUsdc) / 1e6} USDC`);

  console.log(`\n[Deposit] Done! The Mock MPC service will process the deposit action and create the balance commitment.`);
  console.log(`[Deposit] Make sure mock-mpc is running: pnpm run mock-mpc`);
}

main().catch((err) => {
  console.error("[Deposit] Fatal:", err);
  process.exit(1);
});
