/**
 * facilitator.ts — Express facilitator server with the confidential scheme registered.
 *
 * Listens on port 4022 and handles /verify, /settle, /supported, /health routes.
 * With Merces contracts, the real MPC handles balance updates and proof verification
 * on-chain. The facilitator queries an MPC balance-check API before settling.
 *
 * Usage: tsx facilitator.ts
 * Requires: .env file (generated by deploy.ts)
 */

import { config } from "dotenv";
config();

import express from "express";
import axios from "axios";
import {
  createWalletClient,
  http,
  defineChain,
} from "viem";
import { baseSepolia } from "viem/chains";
import { privateKeyToAccount } from "viem/accounts";
import { publicActions } from "viem";
import { x402Facilitator } from "@x402/core/facilitator";
import { toFacilitatorEvmSigner } from "@x402/evm";
import { ConfidentialEvmScheme } from "@x402/evm/confidential/facilitator";
import type { BabyJubJubPoint } from "@x402/evm";
import type {
  PaymentPayload,
  PaymentRequirements,
  Network,
} from "@x402/core/types";

// ── Configuration ──────────────────────────────────────────────────────────────

const RPC_URL = process.env.RPC_URL || "http://127.0.0.1:8545";
const CHAIN_ID = parseInt(process.env.CHAIN_ID || "31337");
const FACILITATOR_KEY = process.env.FACILITATOR_PRIVATE_KEY as `0x${string}`;
const MERCES_ADDRESS = process.env.MERCES_ADDRESS as `0x${string}`;
const MPC_PK1_X = process.env.MPC_PK1_X!;
const MPC_PK1_Y = process.env.MPC_PK1_Y!;
const MPC_PK2_X = process.env.MPC_PK2_X || MPC_PK1_X;
const MPC_PK2_Y = process.env.MPC_PK2_Y || MPC_PK1_Y;
const MPC_PK3_X = process.env.MPC_PK3_X || MPC_PK1_X;
const MPC_PK3_Y = process.env.MPC_PK3_Y || MPC_PK1_Y;

// TODO: Replace with real MPC balance-check endpoint when available.
// The real MPC will expose POST /balance-check { sender, amount } → { sufficient: bool }
// via a multi-party computation (no single party learns the actual balance).
// For now this can point at a lightweight mock or be left unset to skip.
const MPC_BALANCE_CHECK_URL = process.env.MPC_BALANCE_CHECK_URL;

if (!FACILITATOR_KEY || !MERCES_ADDRESS) {
  console.error("Missing required env vars (FACILITATOR_PRIVATE_KEY, MERCES_ADDRESS). Run deploy first.");
  process.exit(1);
}

// ── Chain & Clients ────────────────────────────────────────────────────────────

const chain = CHAIN_ID === 84532
  ? defineChain({ ...baseSepolia, rpcUrls: { default: { http: [RPC_URL] } } })
  : defineChain({
      id: CHAIN_ID,
      name: "Anvil",
      nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
      rpcUrls: { default: { http: [RPC_URL] } },
    });

const account = privateKeyToAccount(FACILITATOR_KEY);
const viemClient = createWalletClient({
  account,
  chain,
  transport: http(RPC_URL),
}).extend(publicActions);

// ── Facilitator Setup ──────────────────────────────────────────────────────────

const evmSigner = toFacilitatorEvmSigner({
  address: account.address,
  readContract: (args) => viemClient.readContract(args),
  verifyTypedData: (args) => viemClient.verifyTypedData(args as Parameters<typeof viemClient.verifyTypedData>[0]),
  writeContract: (args) => viemClient.writeContract(args),
  sendTransaction: (args) => viemClient.sendTransaction(args),
  waitForTransactionReceipt: (args) => viemClient.waitForTransactionReceipt(args),
  getCode: (args) => viemClient.getCode(args),
});

const mpcPk1: BabyJubJubPoint = { x: MPC_PK1_X, y: MPC_PK1_Y };
const mpcPk2: BabyJubJubPoint = { x: MPC_PK2_X, y: MPC_PK2_Y };
const mpcPk3: BabyJubJubPoint = { x: MPC_PK3_X, y: MPC_PK3_Y };
const NETWORK: Network = `eip155:${CHAIN_ID}`;

const facilitator = new x402Facilitator();
facilitator.register(
  NETWORK,
  new ConfidentialEvmScheme({
    signer: evmSigner,
    confidentialToken: MERCES_ADDRESS,
    eip712Domain: { name: "Merces", version: "1" },
    mpcPublicKeys: [mpcPk1, mpcPk2, mpcPk3],
  }),
);

// ── Express Server ─────────────────────────────────────────────────────────────

const app = express();
app.use(express.json({ limit: "10mb" }));

app.post("/verify", async (req, res) => {
  try {
    const { paymentPayload, paymentRequirements } = req.body;

    // Balance check via MPC (if configured)
    if (MPC_BALANCE_CHECK_URL) {
      try {
        const payload = paymentPayload as PaymentPayload;
        const requirements = paymentRequirements as PaymentRequirements;
        const auth = (payload.payload as Record<string, unknown>)?.authorization as Record<string, unknown> | undefined;
        const sender = auth?.sender as string | undefined;
        const amount = requirements?.amount;

        if (sender && amount) {
          const { data } = await axios.post(`${MPC_BALANCE_CHECK_URL}/balance-check`, {
            sender,
            amount,
          });
          if (!data.sufficient) {
            console.log(`[Facilitator] Balance check failed: ${sender} has insufficient funds`);
            return res.json({ isValid: false, invalidReason: "insufficient_confidential_balance" });
          }
          console.log(`[Facilitator] Balance check passed for ${sender}`);
        }
      } catch (err) {
        console.warn("[Facilitator] Balance check unavailable, skipping:", err instanceof Error ? err.message : err);
      }
    }

    const response = await facilitator.verify(
      paymentPayload as PaymentPayload,
      paymentRequirements as PaymentRequirements,
    );
    console.log(`[Facilitator] Verify: isValid=${response.isValid}, payer=${response.payer}, reason=${response.invalidReason ?? "none"}`);
    res.json(response);
  } catch (err) {
    console.error("[Facilitator] Verify error:", err);
    res.status(500).json({ isValid: false, invalidReason: "internal_error" });
  }
});

app.post("/settle", async (req, res) => {
  try {
    const { paymentPayload, paymentRequirements } = req.body;
    const response = await facilitator.settle(
      paymentPayload as PaymentPayload,
      paymentRequirements as PaymentRequirements,
    );
    console.log(
      `[Facilitator] Settle: success=${response.success}, tx=${response.transaction || "N/A"}`,
    );
    res.json(response);
  } catch (err) {
    console.error("[Facilitator] Settle error:", err);
    res.status(500).json({ success: false, errorReason: "internal_error", transaction: "" });
  }
});

app.get("/supported", async (_req, res) => {
  const response = facilitator.getSupported();
  res.json(response);
});

app.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    network: NETWORK,
    facilitator: "confidential-merces",
    contract: MERCES_ADDRESS,
    balanceCheck: MPC_BALANCE_CHECK_URL ? "enabled" : "disabled (no MPC_BALANCE_CHECK_URL)",
  });
});

const PORT = parseInt(process.env.FACILITATOR_PORT || "4022");
app.listen(PORT, () => {
  console.log(`[Facilitator] Listening on http://localhost:${PORT}`);
  console.log(`[Facilitator] Registered confidential scheme for ${NETWORK}`);
  console.log(`[Facilitator] Merces contract: ${MERCES_ADDRESS}`);
  console.log(`[Facilitator] EIP-712 domain: Merces v1`);
  console.log(`[Facilitator] Balance check: ${MPC_BALANCE_CHECK_URL || "disabled"}`);
  console.log(`[Facilitator] Signer: ${account.address}\n`);
});
