/**
 * facilitator.ts — Express facilitator server with the confidential scheme registered.
 *
 * Listens on port 4022 and handles /verify, /settle, /supported, /health routes.
 *
 * Usage: tsx facilitator.ts
 * Requires: .env file (generated by deploy.ts)
 */

import { config } from "dotenv";
config();

import express from "express";
import {
  createPublicClient,
  createWalletClient,
  http,
  defineChain,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { publicActions } from "viem";
import { x402Facilitator } from "@x402/core/facilitator";
import { toFacilitatorEvmSigner } from "@x402/evm";
import { ConfidentialEvmScheme } from "@x402/evm/confidential/facilitator";
import type { BabyJubJubPoint } from "@x402/evm";
import type {
  PaymentPayload,
  PaymentRequirements,
  Network,
} from "@x402/core/types";

// ── Configuration ──────────────────────────────────────────────────────────────

const RPC_URL = process.env.RPC_URL || "http://127.0.0.1:8545";
const CHAIN_ID = parseInt(process.env.CHAIN_ID || "31337");
const FACILITATOR_KEY = process.env.FACILITATOR_PRIVATE_KEY as `0x${string}`;
const PRIVATE_BALANCE_ADDRESS = process.env.PRIVATE_BALANCE_ADDRESS as `0x${string}`;
const MPC_PK_X = process.env.MPC_PK_X!;
const MPC_PK_Y = process.env.MPC_PK_Y!;

if (!FACILITATOR_KEY || !PRIVATE_BALANCE_ADDRESS) {
  console.error("Missing required env vars. Run 'pnpm run deploy' first.");
  process.exit(1);
}

// ── Chain & Clients ────────────────────────────────────────────────────────────

const anvil = defineChain({
  id: CHAIN_ID,
  name: "Anvil",
  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  rpcUrls: { default: { http: [RPC_URL] } },
});

const account = privateKeyToAccount(FACILITATOR_KEY);
const viemClient = createWalletClient({
  account,
  chain: anvil,
  transport: http(RPC_URL),
}).extend(publicActions);

// ── Facilitator Setup ──────────────────────────────────────────────────────────

const evmSigner = toFacilitatorEvmSigner({
  address: account.address,
  readContract: (args) => viemClient.readContract(args),
  verifyTypedData: (args) => viemClient.verifyTypedData(args as Parameters<typeof viemClient.verifyTypedData>[0]),
  writeContract: (args) => viemClient.writeContract(args),
  sendTransaction: (args) => viemClient.sendTransaction(args),
  waitForTransactionReceipt: (args) => viemClient.waitForTransactionReceipt(args),
  getCode: (args) => viemClient.getCode(args),
});

const mpcPk: BabyJubJubPoint = { x: MPC_PK_X, y: MPC_PK_Y };
const NETWORK: Network = `eip155:${CHAIN_ID}`;

const facilitator = new x402Facilitator();
facilitator.register(
  NETWORK,
  new ConfidentialEvmScheme({
    signer: evmSigner,
    confidentialToken: PRIVATE_BALANCE_ADDRESS,
    eip712Domain: { name: "ConfidentialToken", version: "1" },
    mpcPublicKeys: [mpcPk, mpcPk, mpcPk],
  }),
);

// ── Express Server ─────────────────────────────────────────────────────────────

const app = express();
app.use(express.json({ limit: "10mb" }));

app.post("/verify", async (req, res) => {
  try {
    const { paymentPayload, paymentRequirements } = req.body;
    const response = await facilitator.verify(
      paymentPayload as PaymentPayload,
      paymentRequirements as PaymentRequirements,
    );
    console.log(`[Facilitator] Verify: isValid=${response.isValid}, payer=${response.payer}`);
    res.json(response);
  } catch (err) {
    console.error("[Facilitator] Verify error:", err);
    res.status(500).json({ isValid: false, invalidReason: "internal_error" });
  }
});

app.post("/settle", async (req, res) => {
  try {
    const { paymentPayload, paymentRequirements } = req.body;
    const response = await facilitator.settle(
      paymentPayload as PaymentPayload,
      paymentRequirements as PaymentRequirements,
    );
    console.log(
      `[Facilitator] Settle: success=${response.success}, tx=${response.transaction || "N/A"}`,
    );
    res.json(response);
  } catch (err) {
    console.error("[Facilitator] Settle error:", err);
    res.status(500).json({ success: false, errorReason: "internal_error", transaction: "" });
  }
});

app.get("/supported", async (_req, res) => {
  const response = facilitator.getSupported();
  res.json(response);
});

app.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    network: NETWORK,
    facilitator: "confidential-demo",
    contract: PRIVATE_BALANCE_ADDRESS,
  });
});

const PORT = parseInt(process.env.FACILITATOR_PORT || "4022");
app.listen(PORT, () => {
  console.log(`[Facilitator] Listening on http://localhost:${PORT}`);
  console.log(`[Facilitator] Registered confidential scheme for ${NETWORK}`);
  console.log(`[Facilitator] Contract: ${PRIVATE_BALANCE_ADDRESS}`);
  console.log(`[Facilitator] Signer:   ${account.address}\n`);
});
