/**
 * facilitator.ts — Express facilitator server with the confidential scheme registered.
 *
 * Listens on port 4022 and handles /verify, /settle, /supported, /health routes.
 * Includes ZK proof verification via snarkjs.
 *
 * Usage: tsx facilitator.ts
 * Requires: .env file (generated by deploy.ts)
 */

import { config } from "dotenv";
config();

import express from "express";
import axios from "axios";
import {
  createPublicClient,
  createWalletClient,
  http,
  defineChain,
} from "viem";
import { baseSepolia } from "viem/chains";
import { privateKeyToAccount } from "viem/accounts";
import { publicActions } from "viem";
import { x402Facilitator } from "@x402/core/facilitator";
import { toFacilitatorEvmSigner } from "@x402/evm";
import { ConfidentialEvmScheme } from "@x402/evm/confidential/facilitator";
import type { ProofVerifier } from "@x402/evm/confidential/facilitator";
import type { BabyJubJubPoint, Groth16Proof } from "@x402/evm";
import type {
  PaymentPayload,
  PaymentRequirements,
  Network,
} from "@x402/core/types";
import * as snarkjs from "snarkjs";
import { readFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Configuration ──────────────────────────────────────────────────────────────

const RPC_URL = process.env.RPC_URL || "http://127.0.0.1:8545";
const CHAIN_ID = parseInt(process.env.CHAIN_ID || "31337");
const FACILITATOR_KEY = process.env.FACILITATOR_PRIVATE_KEY as `0x${string}`;
const PRIVATE_BALANCE_ADDRESS = process.env.PRIVATE_BALANCE_ADDRESS as `0x${string}`;
const MPC_PK_X = process.env.MPC_PK_X!;
const MPC_PK_Y = process.env.MPC_PK_Y!;
const MPC_BALANCE_CHECK_URL = process.env.MPC_BALANCE_CHECK_URL;

if (!FACILITATOR_KEY || !PRIVATE_BALANCE_ADDRESS) {
  console.error("Missing required env vars. Run 'pnpm run deploy' first.");
  process.exit(1);
}

// ── ZK Verification Key ──────────────────────────────────────────────────────

const vkeyPath = resolve(__dirname, "./artifacts/zk/verification_key.json");
let vkey: Record<string, unknown> | null = null;
try {
  vkey = JSON.parse(readFileSync(vkeyPath, "utf8"));
  console.log("[Facilitator] Loaded ZK verification key");
} catch {
  console.warn("[Facilitator] No ZK verification key found — proof verification disabled");
}

const proofVerifier: ProofVerifier | undefined = vkey
  ? async (proof: Groth16Proof, publicSignals: string[]) => {
      const snarkjsProof = {
        pi_a: [...proof.pA, "1"],
        pi_b: [
          [proof.pB[0][0], proof.pB[0][1]],
          [proof.pB[1][0], proof.pB[1][1]],
          ["1", "0"],
        ],
        pi_c: [...proof.pC, "1"],
        protocol: "groth16",
        curve: "bn128",
      };
      return snarkjs.groth16.verify(vkey!, publicSignals.map(String), snarkjsProof);
    }
  : undefined;

// ── Chain & Clients ────────────────────────────────────────────────────────────

const chain = CHAIN_ID === 84532
  ? defineChain({ ...baseSepolia, rpcUrls: { default: { http: [RPC_URL] } } })
  : defineChain({
      id: CHAIN_ID,
      name: "Anvil",
      nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
      rpcUrls: { default: { http: [RPC_URL] } },
    });

const account = privateKeyToAccount(FACILITATOR_KEY);
const viemClient = createWalletClient({
  account,
  chain,
  transport: http(RPC_URL),
}).extend(publicActions);

// ── Facilitator Setup ──────────────────────────────────────────────────────────

const evmSigner = toFacilitatorEvmSigner({
  address: account.address,
  readContract: (args) => viemClient.readContract(args),
  verifyTypedData: (args) => viemClient.verifyTypedData(args as Parameters<typeof viemClient.verifyTypedData>[0]),
  writeContract: (args) => viemClient.writeContract(args),
  sendTransaction: (args) => viemClient.sendTransaction(args),
  waitForTransactionReceipt: (args) => viemClient.waitForTransactionReceipt(args),
  getCode: (args) => viemClient.getCode(args),
});

const mpcPk: BabyJubJubPoint = { x: MPC_PK_X, y: MPC_PK_Y };
const NETWORK: Network = `eip155:${CHAIN_ID}`;

const facilitator = new x402Facilitator();
facilitator.register(
  NETWORK,
  new ConfidentialEvmScheme({
    signer: evmSigner,
    confidentialToken: PRIVATE_BALANCE_ADDRESS,
    eip712Domain: { name: "ConfidentialToken", version: "1" },
    mpcPublicKeys: [mpcPk, mpcPk, mpcPk],
    proofVerifier,
  }),
);

// ── Express Server ─────────────────────────────────────────────────────────────

const app = express();
app.use(express.json({ limit: "10mb" }));

app.post("/verify", async (req, res) => {
  try {
    const { paymentPayload, paymentRequirements } = req.body;

    // Balance check via Mock MPC (if configured)
    if (MPC_BALANCE_CHECK_URL) {
      try {
        const payload = paymentPayload as PaymentPayload;
        const requirements = paymentRequirements as PaymentRequirements;
        const auth = (payload.payload as Record<string, unknown>)?.authorization as Record<string, unknown> | undefined;
        const sender = auth?.sender as string | undefined;
        const amount = requirements?.amount;

        if (sender && amount) {
          const { data } = await axios.post(`${MPC_BALANCE_CHECK_URL}/balance-check`, {
            sender,
            amount,
          });
          if (!data.sufficient) {
            console.log(`[Facilitator] Balance check failed: ${sender} has insufficient funds`);
            return res.json({ isValid: false, invalidReason: "insufficient_confidential_balance" });
          }
          console.log(`[Facilitator] Balance check passed for ${sender}`);
        }
      } catch (err) {
        console.warn("[Facilitator] Balance check unavailable, skipping:", err instanceof Error ? err.message : err);
      }
    }

    const response = await facilitator.verify(
      paymentPayload as PaymentPayload,
      paymentRequirements as PaymentRequirements,
    );
    console.log(`[Facilitator] Verify: isValid=${response.isValid}, payer=${response.payer}, reason=${response.invalidReason ?? "none"}`);
    res.json(response);
  } catch (err) {
    console.error("[Facilitator] Verify error:", err);
    res.status(500).json({ isValid: false, invalidReason: "internal_error" });
  }
});

app.post("/settle", async (req, res) => {
  try {
    const { paymentPayload, paymentRequirements } = req.body;

    // Send plaintext amount hint to mock MPC BEFORE settling —
    // the hint must be stored before the action appears in the on-chain queue,
    // otherwise the MPC polling loop may process the action before the hint arrives.
    if (MPC_BALANCE_CHECK_URL) {
      const payload = paymentPayload as PaymentPayload;
      const requirements = paymentRequirements as PaymentRequirements;
      const auth = (payload.payload as Record<string, unknown>)?.authorization as Record<string, unknown> | undefined;
      const sender = auth?.sender as string | undefined;
      const receiver = requirements?.payTo;
      const amount = requirements?.amount;
      if (sender && receiver && amount) {
        try {
          await axios.post(`${MPC_BALANCE_CHECK_URL}/transfer-hint`, { sender, receiver, amount });
        } catch (e) {
          console.warn("[Facilitator] Failed to send transfer hint to MPC:", e instanceof Error ? e.message : e);
        }
      }
    }

    const response = await facilitator.settle(
      paymentPayload as PaymentPayload,
      paymentRequirements as PaymentRequirements,
    );
    console.log(
      `[Facilitator] Settle: success=${response.success}, tx=${response.transaction || "N/A"}`,
    );

    res.json(response);
  } catch (err) {
    console.error("[Facilitator] Settle error:", err);
    res.status(500).json({ success: false, errorReason: "internal_error", transaction: "" });
  }
});

app.get("/supported", async (_req, res) => {
  const response = facilitator.getSupported();
  res.json(response);
});

app.get("/health", (_req, res) => {
  res.json({
    status: "ok",
    network: NETWORK,
    facilitator: "confidential-demo",
    contract: PRIVATE_BALANCE_ADDRESS,
    zkProofVerification: !!proofVerifier,
  });
});

const PORT = parseInt(process.env.FACILITATOR_PORT || "4022");
app.listen(PORT, () => {
  console.log(`[Facilitator] Listening on http://localhost:${PORT}`);
  console.log(`[Facilitator] Registered confidential scheme for ${NETWORK}`);
  console.log(`[Facilitator] Contract: ${PRIVATE_BALANCE_ADDRESS}`);
  console.log(`[Facilitator] ZK proof verification: ${proofVerifier ? "enabled" : "disabled"}`);
  console.log(`[Facilitator] Signer:   ${account.address}\n`);
});
