/**
 * generate-wallets.ts — Generates 4 fresh wallets and writes a template .env.sepolia.
 *
 * Run this once before deploying to Base Sepolia. After running, fund the
 * MPC and Facilitator wallets with ETH via a faucet, then run deploy:sepolia.
 *
 * Usage: pnpm run generate-wallets
 */

import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const mpcKey = generatePrivateKey();
const facilitatorKey = generatePrivateKey();
const agentKey = generatePrivateKey();
const serverKey = generatePrivateKey();

const mpc = privateKeyToAccount(mpcKey);
const facilitator = privateKeyToAccount(facilitatorKey);
const agent = privateKeyToAccount(agentKey);
const server = privateKeyToAccount(serverKey);

const BABYJUBJUB_BASE_X = "5299619240641551281634865583518297030282874472190772894086521144482721001553";
const BABYJUBJUB_BASE_Y = "16950150798460657717958625567821834550301663161624707787222815936182638968203";

const envContent = `# Generated by generate-wallets.ts
# Fund these wallets before running deploy:sepolia

# Private keys
MPC_PRIVATE_KEY=${mpcKey}
FACILITATOR_PRIVATE_KEY=${facilitatorKey}
SERVER_PRIVATE_KEY=${serverKey}
AGENT_PRIVATE_KEY=${agentKey}

# Chain
CHAIN_ID=84532
RPC_URL=https://sepolia.base.org

# Contract addresses — filled in by deploy-sepolia.ts
USDC_ADDRESS=0x036CbD53842c5426634e7929541eC2318f3dCF7e
POSEIDON2_ADDRESS=
VERIFIER_ADDRESS=
PRIVATE_BALANCE_ADDRESS=

# Derived addresses
MPC_ADDRESS=${mpc.address}
FACILITATOR_ADDRESS=${facilitator.address}
SERVER_ADDRESS=${server.address}
AGENT_ADDRESS=${agent.address}

# MPC Public Keys (BabyJubJub base point)
MPC_PK_X=${BABYJUBJUB_BASE_X}
MPC_PK_Y=${BABYJUBJUB_BASE_Y}

# Mock MPC service
MPC_BALANCE_CHECK_URL=http://localhost:4023
`;

const envPath = resolve(__dirname, ".env.sepolia");
writeFileSync(envPath, envContent);

console.log("Generated 4 wallets and wrote .env.sepolia\n");
console.log("  MPC (deployer):    ", mpc.address);
console.log("  Facilitator:       ", facilitator.address);
console.log("  Agent:             ", agent.address);
console.log("  Server:            ", server.address);
console.log("");
console.log("Next steps:");
console.log("  1. Fund MPC wallet with ~0.05 ETH on Base Sepolia");
console.log("     https://www.alchemy.com/faucets/base-sepolia");
console.log("  2. Fund Facilitator wallet with ~0.02 ETH");
console.log("  3. Fund Agent wallet with ~0.002 ETH (for approve + deposit gas)");
console.log("  4. Get 20 USDC for Agent from https://faucet.circle.com (Base Sepolia)");
console.log("  5. Run: pnpm run deploy:sepolia");
