/**
 * mock-mpc.ts — Mock MPC network service for Base Sepolia demo.
 *
 * Provides:
 *   - POST /balance-check — facilitator queries sender balance before settling
 *   - GET /health — health check
 *   - GET /status — returns all tracked balances (debugging/dashboard)
 *   - Polling loop: reads action queue from on-chain, processes with dummy proofs
 *
 * Usage: tsx mock-mpc.ts
 * Requires: .env.sepolia (generated by deploy-sepolia.ts)
 */

import { config } from "dotenv";
config();

import express from "express";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import {
  createPublicClient,
  createWalletClient,
  http,
  getAddress,
} from "viem";
import { baseSepolia } from "viem/chains";
import { privateKeyToAccount } from "viem/accounts";
import { publicActions } from "viem";
import { defineChain } from "viem";

// ── Configuration ──────────────────────────────────────────────────────────────

const RPC_URL = process.env.RPC_URL || "https://sepolia.base.org";
const CHAIN_ID = parseInt(process.env.CHAIN_ID || "84532");
const MPC_KEY = process.env.MPC_PRIVATE_KEY as `0x${string}`;
const PRIVATE_BALANCE_ADDRESS = process.env.PRIVATE_BALANCE_ADDRESS as `0x${string}`;
const POLL_INTERVAL_MS = parseInt(process.env.MPC_POLL_INTERVAL || "5000");

if (!MPC_KEY || !PRIVATE_BALANCE_ADDRESS) {
  console.error("Missing required env vars. Run 'pnpm run deploy:sepolia' first.");
  process.exit(1);
}

// ── Chain & Clients ────────────────────────────────────────────────────────────

const chain = CHAIN_ID === 84532
  ? defineChain({ ...baseSepolia, rpcUrls: { default: { http: [RPC_URL] } } })
  : defineChain({
      id: CHAIN_ID,
      name: "Anvil",
      nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
      rpcUrls: { default: { http: [RPC_URL] } },
    });

const account = privateKeyToAccount(MPC_KEY);
const viemClient = createWalletClient({
  account,
  chain,
  transport: http(RPC_URL),
}).extend(publicActions);

const publicClient = createPublicClient({ chain, transport: http(RPC_URL) });

// ── BN254 Prime ────────────────────────────────────────────────────────────────

const BN254_PRIME = BigInt("0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001");
const BATCH_SIZE = 50;

// ── ABI Fragments ──────────────────────────────────────────────────────────────

const PRIVATE_BALANCE_ABI = [
  {
    name: "getActionQueueSize",
    type: "function",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    name: "read_queue",
    type: "function",
    inputs: [{ name: "num_items", type: "uint256" }],
    outputs: [
      { name: "", type: "uint256[]" },
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "action", type: "uint8" },
          { name: "sender", type: "address" },
          { name: "receiver", type: "address" },
          { name: "amount", type: "uint256" },
        ],
      },
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "amount", type: "uint256[3]" },
          { name: "r", type: "uint256[3]" },
          {
            name: "sender_pk",
            type: "tuple",
            components: [
              { name: "x", type: "uint256" },
              { name: "y", type: "uint256" },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    name: "processMPC",
    type: "function",
    inputs: [
      {
        name: "inputs",
        type: "tuple",
        components: [
          { name: "action_index", type: "uint256[50]" },
          { name: "commitments", type: "uint256[100]" },
        ],
      },
      {
        name: "proof",
        type: "tuple",
        components: [
          { name: "pA", type: "uint256[2]" },
          { name: "pB", type: "uint256[2][2]" },
          { name: "pC", type: "uint256[2]" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    name: "getBalanceCommitment",
    type: "function",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    name: "commit",
    type: "function",
    inputs: [
      { name: "input", type: "uint256" },
      { name: "randomness", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
];

// Action enum from Solidity: Dummy=0, Deposit=1, Withdraw=2, Transfer=3
const Action = { Dummy: 0, Deposit: 1, Withdraw: 2, Transfer: 3 } as const;

// ── In-Memory Balance Tracking ─────────────────────────────────────────────────

interface BalanceEntry {
  balance: bigint;
  randomness: bigint;
}

const balances = new Map<string, BalanceEntry>();

// ── Persistence ───────────────────────────────────────────────────────────────

const __mpc_dirname = dirname(fileURLToPath(import.meta.url));
const BALANCE_FILE = resolve(__mpc_dirname, ".mpc-balances.json");

interface PersistedState {
  randomnessCounter: string;
  balances: Record<string, { balance: string; randomness: string }>;
}

function saveBalances() {
  const state: PersistedState = {
    randomnessCounter: randomnessCounter.toString(),
    balances: {},
  };
  for (const [addr, entry] of balances) {
    state.balances[addr] = {
      balance: entry.balance.toString(),
      randomness: entry.randomness.toString(),
    };
  }
  writeFileSync(BALANCE_FILE, JSON.stringify(state, null, 2));
}

function loadBalances() {
  if (!existsSync(BALANCE_FILE)) {
    console.log(`[MPC] No saved state found — starting fresh`);
    return;
  }
  try {
    const state: PersistedState = JSON.parse(readFileSync(BALANCE_FILE, "utf8"));
    randomnessCounter = BigInt(state.randomnessCounter);
    for (const [addr, entry] of Object.entries(state.balances)) {
      balances.set(addr, {
        balance: BigInt(entry.balance),
        randomness: BigInt(entry.randomness),
      });
    }
    console.log(`[MPC] Restored ${balances.size} balance(s) from ${BALANCE_FILE}`);
    for (const [addr, entry] of balances) {
      console.log(`[MPC]   ${addr}: ${(Number(entry.balance) / 1e6).toFixed(6)} USDC`);
    }
  } catch (err) {
    console.warn(`[MPC] Failed to load saved state, starting fresh:`, err instanceof Error ? err.message : err);
  }
}

// Simple randomness generator (deterministic for reproducibility)
let randomnessCounter = BigInt(99999999);
function nextRandomness(): bigint {
  randomnessCounter += BigInt(1);
  return randomnessCounter % BN254_PRIME;
}

loadBalances();

function getBalance(address: string): BalanceEntry {
  return balances.get(address.toLowerCase()) || { balance: BigInt(0), randomness: BigInt(0) };
}

function setBalance(address: string, entry: BalanceEntry) {
  balances.set(address.toLowerCase(), entry);
  saveBalances();
}

// ── Express Server ─────────────────────────────────────────────────────────────

const app = express();
app.use(express.json());

// CORS
app.use((_req, res, next) => {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Content-Type");
  res.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  if (_req.method === "OPTIONS") return res.sendStatus(204);
  next();
});

// ── Transfer Hints (side-channel from facilitator) ─────────────────────────

interface TransferHint {
  sender: string;
  receiver: string;
  amount: bigint;
}

const transferHints: TransferHint[] = [];

app.post("/transfer-hint", (req, res) => {
  const { sender, receiver, amount } = req.body;
  if (!sender || !receiver || amount === undefined) {
    return res.status(400).json({ error: "Missing sender, receiver, or amount" });
  }
  transferHints.push({ sender: sender.toLowerCase(), receiver: receiver.toLowerCase(), amount: BigInt(amount) });
  console.log(`[MPC] Transfer hint received: ${sender} → ${receiver}, ${Number(BigInt(amount)) / 1e6} USDC (${transferHints.length} pending)`);
  return res.json({ ok: true });
});

app.post("/balance-check", (req, res) => {
  const { sender, amount } = req.body;
  if (!sender || amount === undefined) {
    return res.status(400).json({ error: "Missing sender or amount" });
  }

  const entry = getBalance(sender);
  const requestedAmount = BigInt(amount);
  const sufficient = entry.balance >= requestedAmount;

  console.log(
    `[MPC] Balance check: ${sender} has ${entry.balance} units, needs ${requestedAmount} → ${sufficient ? "SUFFICIENT" : "INSUFFICIENT"}`,
  );

  return res.json({ sufficient, balance: entry.balance.toString() });
});

app.get("/health", (_req, res) => {
  res.json({ status: "ok", service: "mock-mpc", contract: PRIVATE_BALANCE_ADDRESS });
});

app.get("/status", (_req, res) => {
  const entries: Record<string, { balance: string; balanceUSDC: string; randomness: string }> = {};
  for (const [addr, entry] of balances) {
    entries[addr] = {
      balance: entry.balance.toString(),
      balanceUSDC: (Number(entry.balance) / 1e6).toFixed(6),
      randomness: entry.randomness.toString(),
    };
  }
  res.json({ balances: entries, pollInterval: POLL_INTERVAL_MS });
});

const PORT = parseInt(process.env.MPC_PORT || "4023");
app.listen(PORT, () => {
  console.log(`[MPC] Mock MPC service listening on http://localhost:${PORT}`);
  console.log(`[MPC] Contract: ${PRIVATE_BALANCE_ADDRESS}`);
  console.log(`[MPC] Operator: ${account.address}`);
  console.log(`[MPC] Poll interval: ${POLL_INTERVAL_MS}ms\n`);
});

// ── Polling Loop ───────────────────────────────────────────────────────────────

let processing = false;

async function pollAndProcess() {
  if (processing) return;
  processing = true;

  try {
    // 1. Check queue size
    const queueSize = await publicClient.readContract({
      address: PRIVATE_BALANCE_ADDRESS,
      abi: PRIVATE_BALANCE_ABI,
      functionName: "getActionQueueSize",
    }) as bigint;

    // Queue always has at least 1 (dummy at index 0)
    if (queueSize <= 1n) {
      return;
    }

    const itemCount = Number(queueSize) - 1;
    console.log(`[MPC] Action queue has ${itemCount} pending action(s)`);

    // 2. Read queue
    const [keys, actions, ciphertexts] = await publicClient.readContract({
      address: PRIVATE_BALANCE_ADDRESS,
      abi: PRIVATE_BALANCE_ABI,
      functionName: "read_queue",
      args: [BigInt(Math.min(itemCount, BATCH_SIZE))],
    }) as [bigint[], Array<{ action: number; sender: string; receiver: string; amount: bigint }>, unknown[]];

    // 3. Build TransactionInput
    const actionIndices: bigint[] = new Array(BATCH_SIZE).fill(BigInt(0));
    const commitments: bigint[] = new Array(BATCH_SIZE * 2).fill(BigInt(0));

    for (let i = 0; i < keys.length; i++) {
      const action = actions[i];
      const key = keys[i];
      actionIndices[i] = key;

      console.log(
        `[MPC] Processing action ${key}: type=${action.action} sender=${action.sender} receiver=${action.receiver}`,
      );

      if (action.action === Action.Transfer) {
        // Look up plaintext amount from facilitator's side-channel hint
        const hintIdx = transferHints.findIndex(
          (h) => h.sender === action.sender.toLowerCase() && h.receiver === action.receiver.toLowerCase(),
        );
        let plaintextAmount: bigint;
        if (hintIdx >= 0) {
          plaintextAmount = transferHints[hintIdx].amount;
          transferHints.splice(hintIdx, 1);
          console.log(`[MPC]   Transfer: ${Number(plaintextAmount) / 1e6} USDC (from facilitator hint)`);
        } else {
          // No hint available — skip this action to avoid corrupting balances
          // with garbage from encrypted ciphertext shares
          console.log(`[MPC]   Transfer: skipping (no hint available, ciphertext is encrypted)`);
          continue;
        }

        // Update balances
        const senderEntry = getBalance(action.sender);
        const receiverEntry = getBalance(action.receiver);

        const newSenderBalance = senderEntry.balance - plaintextAmount;
        const newSenderRandomness = nextRandomness();
        const newReceiverBalance = receiverEntry.balance + plaintextAmount;
        const newReceiverRandomness = nextRandomness();

        // Compute new commitments on-chain
        const senderCommitment = await publicClient.readContract({
          address: PRIVATE_BALANCE_ADDRESS,
          abi: PRIVATE_BALANCE_ABI,
          functionName: "commit",
          args: [newSenderBalance >= 0n ? newSenderBalance : BigInt(0), newSenderRandomness],
        }) as bigint;

        const receiverCommitment = await publicClient.readContract({
          address: PRIVATE_BALANCE_ADDRESS,
          abi: PRIVATE_BALANCE_ABI,
          functionName: "commit",
          args: [newReceiverBalance, newReceiverRandomness],
        }) as bigint;

        commitments[i * 2] = senderCommitment;
        commitments[i * 2 + 1] = receiverCommitment;

        // Update local state
        setBalance(action.sender, { balance: newSenderBalance >= 0n ? newSenderBalance : BigInt(0), randomness: newSenderRandomness });
        setBalance(action.receiver, { balance: newReceiverBalance, randomness: newReceiverRandomness });

        console.log(
          `[MPC]   Sender ${action.sender}: ${Number(senderEntry.balance) / 1e6} → ${Number(newSenderBalance >= 0n ? newSenderBalance : BigInt(0)) / 1e6} USDC`,
        );
        console.log(
          `[MPC]   Receiver ${action.receiver}: ${Number(receiverEntry.balance) / 1e6} → ${Number(newReceiverBalance) / 1e6} USDC`,
        );
      } else if (action.action === Action.Deposit) {
        const amount = action.amount; // Plaintext amount for deposits
        const receiverEntry = getBalance(action.receiver);
        const newBalance = receiverEntry.balance + amount;
        const newRandomness = nextRandomness();

        const receiverCommitment = await publicClient.readContract({
          address: PRIVATE_BALANCE_ADDRESS,
          abi: PRIVATE_BALANCE_ABI,
          functionName: "commit",
          args: [newBalance, newRandomness],
        }) as bigint;

        commitments[i * 2] = BigInt(0); // sender commitment must be 0 for deposits
        commitments[i * 2 + 1] = receiverCommitment;

        setBalance(action.receiver, { balance: newBalance, randomness: newRandomness });
        console.log(`[MPC]   Deposit: ${Number(amount) / 1e6} USDC to ${action.receiver}`);
      } else if (action.action === Action.Withdraw) {
        const amount = action.amount;
        const senderEntry = getBalance(action.sender);
        const newBalance = senderEntry.balance >= amount ? senderEntry.balance - amount : BigInt(0);
        const newRandomness = nextRandomness();

        const senderCommitment = await publicClient.readContract({
          address: PRIVATE_BALANCE_ADDRESS,
          abi: PRIVATE_BALANCE_ABI,
          functionName: "commit",
          args: [newBalance, newRandomness],
        }) as bigint;

        commitments[i * 2] = senderCommitment;
        commitments[i * 2 + 1] = BigInt(0); // receiver commitment must be 0 for withdrawals

        setBalance(action.sender, { balance: newBalance, randomness: newRandomness });
        console.log(`[MPC]   Withdraw: ${Number(amount) / 1e6} USDC from ${action.sender}`);
      }
    }

    // 4. Build dummy Groth16 proof (MockVerifier accepts anything)
    const proof = {
      pA: [BigInt(0), BigInt(0)] as [bigint, bigint],
      pB: [[BigInt(0), BigInt(0)], [BigInt(0), BigInt(0)]] as [[bigint, bigint], [bigint, bigint]],
      pC: [BigInt(0), BigInt(0)] as [bigint, bigint],
    };

    const inputs = {
      action_index: actionIndices as unknown as readonly bigint[] & { length: 50 },
      commitments: commitments as unknown as readonly bigint[] & { length: 100 },
    };

    // 5. Call processMPC on-chain
    console.log(`[MPC] Submitting processMPC with ${keys.length} action(s)...`);

    const txHash = await viemClient.writeContract({
      address: PRIVATE_BALANCE_ADDRESS,
      abi: PRIVATE_BALANCE_ABI,
      functionName: "processMPC",
      args: [inputs, proof],
    });

    console.log(`[MPC] processMPC tx: ${txHash}`);
    const receipt = await publicClient.waitForTransactionReceipt({ hash: txHash });
    console.log(
      `[MPC] processMPC confirmed in block ${receipt.blockNumber} (gas: ${receipt.gasUsed})\n`,
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[MPC] Poll error: ${msg.slice(0, 500)}`);
  } finally {
    processing = false;
  }
}

// Start polling
setInterval(pollAndProcess, POLL_INTERVAL_MS);
console.log(`[MPC] Polling loop started (every ${POLL_INTERVAL_MS / 1000}s)\n`);

// Run once immediately
pollAndProcess();
