/**
 * server.ts — Express resource server with confidential x402 payment middleware.
 *
 * Protects /v1/sentiment behind a $0.05 USDC confidential payment.
 * Listens on port 4021.
 *
 * Usage: tsx server.ts
 * Requires: .env file (generated by deploy.ts) and facilitator running on :4022
 */

import { config } from "dotenv";
config();

import express from "express";
import { defineChain } from "viem";
import { baseSepolia } from "viem/chains";
import { paymentMiddleware, x402ResourceServer } from "@x402/express";
import { HTTPFacilitatorClient } from "@x402/core/server";
import { ConfidentialEvmScheme } from "@x402/evm/confidential/server";
import type { Network } from "@x402/core/types";

// ── Configuration ──────────────────────────────────────────────────────────────

const CHAIN_ID = parseInt(process.env.CHAIN_ID || "31337");
const SERVER_ADDRESS = process.env.SERVER_ADDRESS as `0x${string}`;
const USDC_ADDRESS = process.env.USDC_ADDRESS as `0x${string}`;
const FACILITATOR_URL = process.env.FACILITATOR_URL || "http://localhost:4022";

if (!SERVER_ADDRESS || !USDC_ADDRESS) {
  console.error("Missing required env vars. Run 'pnpm run deploy' first.");
  process.exit(1);
}

const NETWORK: Network = `eip155:${CHAIN_ID}`;

// ── Express Server ─────────────────────────────────────────────────────────────

const facilitatorClient = new HTTPFacilitatorClient({ url: FACILITATOR_URL });
const app = express();

// Payment middleware protects routes
app.use(
  paymentMiddleware(
    {
      "GET /v1/sentiment": {
        accepts: [
          {
            scheme: "confidential",
            price: { amount: "50000", asset: USDC_ADDRESS },
            network: NETWORK,
            payTo: SERVER_ADDRESS,
          },
        ],
        description: "Premium sentiment analysis",
        mimeType: "application/json",
      },
    },
    new x402ResourceServer(facilitatorClient).register(
      NETWORK,
      new ConfidentialEvmScheme({ asset: USDC_ADDRESS }),
    ),
  ),
);

// Protected endpoint
app.get("/v1/sentiment", (req, res) => {
  const ticker = (req.query.ticker as string) || "ETH";
  console.log(`[Server] Serving sentiment data for ${ticker}`);
  res.json({
    ticker,
    sentiment: 0.73,
    signal: "bullish",
    confidence: "high",
    sources: 1247,
    timestamp: new Date().toISOString(),
  });
});

// Health check
app.get("/health", (_req, res) => {
  res.json({ status: "ok", network: NETWORK, payTo: SERVER_ADDRESS });
});

const PORT = parseInt(process.env.SERVER_PORT || "4021");
app.listen(PORT, () => {
  console.log(`[Server] Listening on http://localhost:${PORT}`);
  console.log(`[Server] /v1/sentiment protected — $0.05 USDC (confidential)`);
  console.log(`[Server] PayTo: ${SERVER_ADDRESS}`);
  console.log(`[Server] Facilitator: ${FACILITATOR_URL}\n`);
});
